### ISSUE TITLE
Audit Jupyter Lab extensions

### ISSUE THREAD

**Issue by ca-scribner** [StatCan/kubeflow-containers#102]
Review the Jupyter Lab extensions installed in the Jupyter servers images.  Objectives are to:
* Find and remove any extensions that are unneeded in order to reduce the potential for bugs/breakage
* Identify any required extensions that are not working properly and either fix or create cards to fix

**Comment by brendangadd** [comment]
@ca-scribner 
This is so great! Some initial thoughts:
* @frazs is probably best to see if there's a reason for some of the stuff you found that looks weird. Lots of good extension experience from wrestling with remote-desktop and such.
* jupyterlab-plotly, jupyterlab-dash, jupyter-matplotlib: worth further investigation to see how they are used and if they are fully working as intended.
* Image inheritance approach: good ideas in here, and we should probably have a focused discussion.
* We should pin our dependencies. Not just for best practice, but because I think Jupyter extensions are notorious for not playing so well and having version incompatibilities.
* For extensions that mostly work, but don't quite do 100% of what they're supposed to, we should put the effort into cleaning that up.
* Pretty much every comment you made is worth an issue.

**Comment by brendangadd** [comment]
From above comment, I'm thinking next steps:
* Create a Jupyter cleanup epic for tracking
* @ca-scribner tells us what to do, wielding issues with a tyrannical fist (and linking them to epic)
* Start having devs pick up issues from the epic

**Comment by ca-scribner** [comment]
I'll wait a day or so for comments, then I can make an epic (or maybe just make this into an epic?) and spawn issues for the bullets

Agreed with the version pinning.  Our extensions tend not to be pinned.  Also noticed we don't pin our Dockerfile inheritance during builds, so we might not build what we expect if two builds occur at once (see [this issue](https://github.com/StatCan/kubeflow-containers/issues/101) - and I'm not sure I'm right on this).  In any case easy to fix, especially if we go to Dockerfile's that accept an `ARG` for upstream image.

**Comment by ca-scribner** [comment]
Closing this issue.  All subsequent issues are now tracked in separate epics StatCan/jupyter-lab#111 and StatCan/jupyter-lab#112
