### ISSUE TITLE
Remove Go Kernel from Jupyterlab Images

### ISSUE THREAD

**Issue by ca-scribner** [StatCan/kubeflow-containers#103]
Kernel doesn't work (?) right now and we don't have any users for it.  Remove it from our stack?  Is it installed in an upstream image that we inherit or do we install it explicitly?

**Comment by ca-scribner** [comment]
@brendangadd / @Ito-Matsuda awkward clarification - are we trying to remove `go` or the go jupyter **kernel**?  In my head it was just the kernel (eg: we don't see `go` on the kernel page in jupyter) but we still have `go` installed.  

...although I'm not advocating for either.  Not sure if anyone uses `go` on the platform?

**Comment by Ito-Matsuda** [comment]
Sorry that's on me completely. The issue does say **just the kernel** but I interpreted it as more

**Comment by ca-scribner** [comment]
Yeah, but now that you've interpreted it that way I'm not sure if I misinterpreted the original conversation or not so it's good it came up :)

**Comment by Ito-Matsuda** [comment]
Duplicating slack message with @brendangadd here

Jose:
Quick question because unsure if you had the time to view Andrew's comment
I just removed everything Go related (yes even though it says KERNEL -likely came from me not understanding it fully, but I now see which part of the Dockerfile is the kernel introduction)
Andrew pointed this out to me and just wants to confirm that it's just the kernel to be removed.
Can just react with :+1: for just Kernel removal or :portalparrot: for everything

Brendan:
That's actually my bad; I didn't know we had more than the Kernel in there for Golang. I think this one's a portal party parrot.
