### ISSUE TITLE
Look into a more maintainable model for these images

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/kubeflow-containers#147]
The current maintenance of these images is a pain. Resolving this will require more than one ticket, but the purpose of this issue is to try to investigate some ideas.

## Integration with docker-stacks

How can we keep our base images up-to-date better, without accidentally introducing breakage.

Thoughts:
- We need to stay better up-to-date with docker-stacks
- We need integration testing for checking compatibility with our JupyterLab plugins
- We probably need better automation for monitoring upstream

## Our base | ML-Tooling could be split up better

Our ML-Tooling approach probably needs work. Some things like conda environments (possibly pre-packaged ones) might be useful. In general, the ML-Tooling is up to the user, so maybe we should be less involved in that space.

# General ideas

## Buildah?
The makefile based approach for creating the Dockerfiles is interesting. Another tool that might be worth looking at is [buildah](https://github.com/containers/buildah).

## Process for "one-off" user images?

We might also consider a better workflow for accommodating user requests within an image. As an example, some members of my team recently needed access to Selenium & Chrome in order to write some web-scraping code. They had a DAaaS team-member build one for them manually so that they could use this in a Jupyter Notebook. This approach seems too cumbersome. Ideally users would have a simple workflow for creating their own images.

## Ansible &/or a manual access into the images?

Weird idea, could we simply open a door into the images via ansible? Instead of rebuilding the images, could we open up the means to do ad-hoc installs into the container at run-time instead of build time? (This may be **WORSE** since it bypasses scanning.)

**Comment by blairdrummond** [comment]
CC @justbert @ca-scribner @brendangadd

**Comment by ca-scribner** [comment]
Generally agreed - good summary!

# Maintenance/docker-stacks

* I don't know if staying up to date with docker-stacks helps or hurts us from maintainability (more frequent syncs leads to more frequent breaks), but it would be good to keep current if it doesn't add effort
* upstream monitoring (both docker-stacks and any other pinned dependency) would be nice.  It would be neat if we could have a declarative way of keeping our dockerfiles up to date for packages we know can be trusted.  Not sure which way is best, but we'd like to achieve something like:
```
FROM docker-stacks/minimal-notebook:KEEP_UPDATED
RUN apt get install some_program=KEEP_UPDATED

# Or maybe: 
RUN SOME_PROGRAM_KEEP_UPDATED_PLACEHOLDER

# Something that shouldn't be updated
RUN apt get install some_old_program=1.2.3
```
(I think some of this exists for python package management at least)
* our bases are definitely messy, but it is partly because we inherit that from docker-stacks.  
* not quite in scope yet but it will be: github's ~13GB limit in their CI.  We haven't been totally blocked by this yet, but several of our images are >12GB and it is only a matter of time.  

# Custom images

* I don't know what to do, but we need to do something imo.  Best state would be a security model that can tolerate malicious user containers (then we can just whitelist anything).  Otherwise, maybe something like the container building service Justin put together internally?  So users could just do something like `container_submit.sh -f MyDockerfile -t myTag .`, then wait a few minutes for a built, scanned version of that to be available in `acr/myName/myTag` or similar.  

# User manipulating images

* We could have an on-the-fly declarative way to get custom images built from whitelisted tools.  Something like a UI where user selects from whitelisted stuff and we build/cache an image on the fly:
  * [x] python
  * [x] tensorflow
  * [ ] pytorch
  * [x] some binary
I'm kinda stealing this from Metaflow, which for python packages lets you do this (you give it a {package: version} dict and builds that env for you (or if it's been built previously, it pulls an existing one from the cache)).  This would allow custom images, but is overkill useless except for conflicting dependencies.  Ignoring conflicting dependencies, the easier solution would just be having a standard image where **everything** comes pre-installed

**Comment by ca-scribner** [comment]
Another painpoint I've noticed for our kubeflow-images is that we seem to corrupt conda's environment graphing somehow.  

Before any `conda install`, conda maps the current environment.  But for some of the later images (ML image, etc), sometimes conda takes 20-30 minutes to resolve the environment before installing a new package (and sometimes it fails entirely).   My guess is that having many interlaced `conda installs` might be the cause?  Like:
```
FROM something-that-installed-in-conda

RUN conda install ...
RUN other stuff
RUN conda install ...
...
```
Maybe combining all the conda installs into a single one would fix this, but since we have a stack of Docker images that inherit from each other that's not ideal.

Maybe other ways to solve would be packaging conda environments on their own separate from our images?

**Comment by ca-scribner** [comment]
Kinda related - Christian has gotten bit a bunch by how since conda/pip packages are installed on home drives, but home drives are ephemeral, pods can lose their package installations.  It isn't a huge painpoint for management, but maybe can be solved at the same time.
