### ISSUE TITLE
Add clean-layer to all pip/conda installs in all layers

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/kubeflow-containers#256]
We wrongfully double the size of most installs if we forget `fix-permissions`

CC @ca-scribner

**Comment by ca-scribner** [comment]
This is explained in more detail now in https://github.com/StatCan/kubeflow-containers#other-development-notes.   The problem can exist for any file that we want users to have permissions for, but the main culprits are `pip install`/`conda install`.  The way this manifests in the worst case is we do something like

```
RUN pip install someBigThing &&
         conda install someOtherBigThing

...

RUN pip install someUnrelatedThing &&
         fix-permissions $CONDA_DIR && \
         fix-permissions /home/$NB_USER
```

Because of how docker layers work, the latter RUN will `fix-permissions` for the entire CONDA_DIR, including both new files for `someUnrelatedThing` and the `someBigThing`/`someOtherBigThing`, which causes the `someBigThing`/`someOtherBigThing` to be **duplicated** in the second RUN statement, potentially adding GBs to the resulting docker image.

**Comment by ca-scribner** [comment]
@rohank07 this is a pretty simple issue but it gets you into the main notebook repo and some docker building etc, plus it is just a good thing to know about if you do future development in this repo.  Let me or @wg102 know if you have any questions, we're happy to help!

**Comment by rohank07** [comment]
After a squash of the remote-desktop image the size was 10.4GB; before it was 10.9 GB.
