### ISSUE TITLE
jupyterlab cell execution information extension

### ISSUE THREAD

**Issue by chritter** [StatCan/kubeflow-containers#39]
Hello,
It would be great to install the extension as in https://stackoverflow.com/questions/56843745/automatic-cell-execution-timing-in-jupyter-lab to allow monitoring the execution time and date. This is a great feature which I am used to from Spark Databricks.

**Comment by saffaalvi** [comment]
When a new notebook server is created using `minimal-notebook-cpu` or a custom image for `minimal-notebook-cpu`, if there is a new volume attached to it, these changes to the cell execution time and theme **are not** being applied. If the "Don't use Persistent Storage for User's home" option is chosen, then the changes **are** applied in the notebook. 

Need to find a way to make these changes stick even when a server is created with a _new_ workspace volume mounted to the notebook. I'm not sure if this is because of the location of the user settings file being stored in ` /home/$NB_USER/.jupyter/lab/user-settings/@jupyterlab/notebook-extension` or if the user settings are being overridden by the persistent storage. This may also be resolved if the `overrides.json` method was implemented instead.
