### ISSUE TITLE
ml-workspace ensure /workspace is persistent disk

### ISSUE THREAD

**Issue by chritter** [StatCan/kubeflow-containers#54]
Hello,
Please ensure that the disk /workspace used in ml-workspace is a persistent disk to avoid data loss when the notebook server shut down.

Best,
Christian

**Comment by frazs** [comment]
Since /home/jovyan is already set up as the mount point for a persistent volume on notebook server creation, an easy-to-immediately-implement solution would be to either make /home/jovyan be the workspace, or to make the workspace be a subfolder inside /home/jovyan (e.g. /home/jovyan/workspace). 

Would either be suitable for you? Which do you prefer?

@blairdrummond and @brendangadd we've spoken about this and IIRC you wanted to go with /home/jovyan to be consistent with other images. That option is ready to be submitted as a PR (I considered the non-persistent separate workspace an unwanted component per #43), but changing it to a subdirectory would be trivial. I'll PR either option tomorrow morning or as soon as I have an answer. 

So far, I had tentatively set the `WORKSPACE_HOME` environment variable to `home/${NB_USER}` (works, reversible, and easier than removing the entire concept of a workspace directory entirely, as that variable is referenced in multiple resource files). I also changed the default Thunar GUI file browser setting to not display hidden directories (various `.config` types) for less clutter (a user can set this back in the view options). I had also removed the shortcut to the workspace directory from the desktop as it is redundant to the Home shortcut in this case, but that is also trivial to put back.

**Comment by frazs** [comment]
Confirmed WORKSPACE_HOME at `home/${NB_USER}` in today's meeting, sending off a PR shortly :smile:
