### ISSUE TITLE
ml-workspace: copy/paste into VNC session

### ISSUE THREAD

**Issue by chritter** [StatCan/kubeflow-containers#56]
Hello,
It would be great to be able to copy and past text directly into your VNC session of the ml-workspace setup.

Thanks!

**Comment by frazs** [comment]
This is a browser based issue (clipboard sharing) and I am not sure how difficult or feasible it would be to implement. I found this lead, but it may be outdated and the linked issues present further complexities.

https://github.com/novnc/noVNC/issues/509#issuecomment-399620468

**Comment by chritter** [comment]
@frazs Thank you for looking into this! Do you know how to use the JS code?

**Comment by frazs** [comment]
I'm not sure, maybe in here: https://github.com/StatCan/kubeflow-containers-desktop/blob/master/base/resources/novnc/vnc.html

**Comment by frazs** [comment]
Disregard the code. `Ctrl+c` and `Ctrl+v` is already supported as-is without it. This works both ways (local to vnc, vnc to local) on Chrome. Unfortunately, it only works one-way (vnc to local) on Firefox, and there isn't anything I can do about that: Firefox does not currently support the clipboard.readText function that would allow your local clipboard's contents to be transferred directly to the VNC session without the use of the intermediary input box in the lefthand VNC panel. 

However, you had mentioned that you are using a Mac keyboard. You may not be seeing this functionality because the code specifically checks `e.ctrlKey` (the event that `Ctrl` was pressed) whereas you are using `Command`. I can try checking for `e.metaKey` as well, but I've read (although perhaps this is outdated) that while most browsers map `Command` to the `metaKey`, Chrome instead maps `Control`. 

But it's worth a test, and perhaps there is another browser that both maps `Command` to `metaKey` and supports both clipboard directions.

**Comment by blairdrummond** [comment]
Does MacOS make use of the Super key at all? That might be another option...

On Linux (under X11), I use XModmap to remap my modifier keys (like Super -> Alt); MacOS is still using X11 as far as I know, so you might be able to achieve this functionality that way.

**Comment by chritter** [comment]
I tried `xmodmap` to switch `control` and `alt`/`command` keys but no success.

**Comment by frazs** [comment]
I'd like for this to remain open as long as it is unresolved. Perhaps you or another Mac user will have some time available in the future, or I'll get access to a Mac keyboard or the means to simulate one.
