### ISSUE TITLE
remote-desktop(vscode): fix/faciliate Python testing

### ISSUE THREAD

**Issue by frazs** [StatCan/kubeflow-containers#92]
- [x] Attempting to do `Command Palette -> Python: Configure Tests` with `ms-python.python` version `2020.6.91350` gives a `Command 'Python: Configure Tests' resulted in an error (command 'python.configureTests' not found)`. Replace this extension with a version that works. Christian has had success with `2020.3.69010a` but a more recent one (or perhaps even newer one) may also work.
- ~~[ ] Install `pylint`~~
- ~~[ ] Install `pytest`~~

**Comment by frazs** [comment]
@chritter When you replaced `ms-python.python` with version `2020.3.69010a`, how did you do that? 

An important matter to verify for anyone who will be tackling this issue is whether this is a problem with the version, or with the installation method.

**Comment by frazs** [comment]
As Brendan brought up, in today's Sprint Planning, @chritter can you confirm whether there is a good reason for pylint and pytest to be pre-installed onto the image? Or would it be sufficient for the ms-python.python extension to be fixed and for users to install pylint and pytest themselves?

**Comment by brendangadd** [comment]
With the Python extension fixed, VS Code will ask the user if they want to install `pylint` and `pytest`, with a one-click installation. That's actually pretty clean:

* We don't need to keep those packages updated.
* It's ultra easy for the user to get them.
* Best practice is to use a virtual environment for your project, which should include dev dependencies.
  * `pytest` etc. should be in `requirements.txt` or whatever dep management tool/file you're using.
  * VS Code detects and uses virtual environments, so it _should_ (@wg102 will verify) install those tools into the active virtual environment if the user chooses to install via the extension's prompt.
  * When VS Code is using your virtual environment, and you're following best practices, it will just find and use the dev deps.

So that gives consistent support across a variety of use cases without polluting the environment.

All that to say: as long as @wg102 find venv is used as expected, don't include the extra packages in the image. Just fix the extension so the user can pull them in one click.

/cc @frazs @chritter

**Comment by wg102** [comment]
I can confirm that the VS Code detects and uses virtual environments. When the user installs the extensions/tools it detects the venv and suggests to add it into the active virtual environment .
