### ISSUE TITLE
JupyterLab responsiveness issue

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/kubeflow-containers#98]
It looks like some extensions are causing slow-downs on JupyterLab

https://github.com/jupyterlab/jupyterlab-git/issues/667

I think we should look into profiling the different extensions and how they're affecting performance. We'll also need to follow that issue ^ and update our git-extension version once it gets updated.

CC @ca-scribner

**Comment by blairdrummond** [comment]
Resolved by https://github.com/StatCan/kubeflow-containers/pull/99

**Comment by blairdrummond** [comment]
Was a Kale issue. @frazs is investigating what's up with Kale

**Comment by frazs** [comment]
The issue was Kale-adjacent. The slowdown came from loading an enormous, >65 MB vendors~main[bunch of alphanumerics].js file. Normally, this file is around 10MB, which is still pretty large but we do have a lot of extensions. It tends to balloon when JupyterLab builds in dev instead of prod mode. By default, `jupyter lab build` builds in prod, but for some reason after the `jupyter labextension install . ` for Kale, it switched to dev.

Changing from `jupyter lab build` to `jupyter lab build -dev-build=False` when Kale is present resolves this issue. It is also possible to add `-dev-build=False` to `jupyter labextension install . `, but when I tested this there was no further reduction in vendors~main and the image size increased by 500MB, so that doesn't seem wroth it.

**Comment by frazs** [comment]
That said even loading 10MB can cause some lag, especially on slower connections, so if there are spare cycles it could be worth poking to see if something's contributing to the bulk of that.
